Reservation.create!([
  {user_id: nil, spa_id: 1, arrival_date: "2016-01-01", first_name: "Bob", email: "Bob@sukit.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-12-08", first_name: "adfas", email: "adfa", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: nil, first_name: "adfsa", email: "adfas", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-11-08", first_name: "adfsas", email: "adfsad", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-04-08", first_name: "afda", email: "adf@gmco.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-12-08", first_name: "sd", email: "sada", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: nil, first_name: "adfsa", email: "adfas", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: nil, first_name: "afdsdfadfsa", email: "adfasadfsas", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-12-08", first_name: "adfsfdas", email: "adfsdas", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-12-08", first_name: "adfsfdas", email: "adfsdas", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: nil, arrival_date: nil, first_name: nil, email: nil, date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-20", first_name: "adfa", email: "afdas", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-22", first_name: "new", email: "new", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-08", first_name: "adfa", email: "adffads", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: "2015-08-11", first_name: "Adam", email: "adaf@", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-05", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-07", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-07", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-07", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-22", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-20", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: "2015-08-14", first_name: "Adam", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: nil, first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-13", first_name: "Adam", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 4, arrival_date: "2015-08-05", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-08", first_name: "Don", email: "don@don.johnson.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-15", first_name: "Adam", email: "adam@adfjads.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-12", first_name: "John", email: "adamf@adfd.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: "2015-08-13", first_name: "adfds", email: "adfsa", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: "2015-08-10", first_name: "sd", email: "sda", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: nil, first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 5, arrival_date: "2015-08-07", first_name: "gfgs", email: "sfgs@alg.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-15", first_name: "adf", email: "adf", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-05", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-10", first_name: "sda", email: "adf", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-03", first_name: "adf", email: "adfa", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: "2015-08-20", first_name: "adf", email: "adfs@adsf.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: "2015-08-20", first_name: "adf", email: "adfs@adsf.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: "2015-08-20", first_name: "adf", email: "adfs@adsf.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-16", first_name: "adsfa", email: "asdf", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-16", first_name: "adsfa", email: "asdf", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-12", first_name: "saD", email: "afs", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-11", first_name: "saD", email: "afs", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-11", first_name: "saD", email: "afs", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-11", first_name: "saD", email: "afs", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-11", first_name: "saD", email: "afs", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-11", first_name: "saD", email: "afs", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-27", first_name: "ds", email: "sa", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-27", first_name: "ds", email: "sa", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-27", first_name: "ds", email: "sa", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-27", first_name: "ds", email: "sa", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 10, arrival_date: "2015-08-13", first_name: "adfsas", email: "adfas@asdglm.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 10, arrival_date: "2015-08-13", first_name: "adfsas", email: "adfas@asdglm.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 10, arrival_date: "2015-08-13", first_name: "adfsas", email: "adfas@asdglm.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-18", first_name: "adfs", email: "afds@ada. com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-18", first_name: "adfs", email: "afds@ada. com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-18", first_name: "adfs", email: "afds@ada. com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-17", first_name: "asd", email: "afda@cadf.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-17", first_name: "asd", email: "afda@cadf.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-04", first_name: "asdf", email: "adsfsa@asdgln.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-04", first_name: "asdf", email: "adsfsa@asdgln.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 4, arrival_date: "2015-08-19", first_name: "asdf", email: "adsfsa@asdgln.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-13", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-07", first_name: "Jogn", email: "ajls@doe.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-16", first_name: "adsf", email: "adf", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-13", first_name: "adf", email: "afd", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-13", first_name: "adf", email: "afd", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-16", first_name: "adsf", email: "adf", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-16", first_name: "adsf", email: "adf", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-16", first_name: "adsf", email: "adf", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-04", first_name: "adfls;", email: "adjka@kagac.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-26", first_name: "Add", email: "sd", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-26", first_name: "Add", email: "sd", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-26", first_name: "Add", email: "sd", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-20", first_name: "sad", email: "sda", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-26", first_name: "Add", email: "sd", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-13", first_name: "adf", email: "afd", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-14", first_name: "adf", email: "afd@dwlasjf.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-03", first_name: "adfa", email: "afda", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-17", first_name: "adsf", email: "afd@caom.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 10, arrival_date: "2015-08-11", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-12", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: "2015-08-16", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 5, arrival_date: "2015-08-11", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: "2015-08-04", first_name: "asfdas", email: "adfsfs", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-05", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-18", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-05", first_name: "adam", email: "adga@calv.om", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-13", first_name: "adam", email: "adsfa@dgla.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-13", first_name: "adam", email: "adsfa@dgla.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-13", first_name: "adam", email: "adsfa@dgla.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-13", first_name: "adam", email: "adsfa@dgla.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-13", first_name: "adam", email: "adsfa@dgla.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-13", first_name: "adam", email: "adsfa@dgla.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-01", first_name: "adfa", email: "adsfas", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 2, arrival_date: "2015-08-12", first_name: "Adam", email: "Poo", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: "2015-08-05", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-09-02", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-03", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-13", first_name: "adfsfdas", email: "afdsda@dlc.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 4, arrival_date: "2015-08-03", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: "2015-08-11", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-04", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: "2015-08-11", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 3, arrival_date: "2015-08-05", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-04", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-11", first_name: "", email: "", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-11", first_name: "adf", email: "adfa", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-11", first_name: "adf", email: "adfa", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-11", first_name: "af", email: "afd", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-04", first_name: "adf", email: "afddas", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-10", first_name: "asd", email: "adfa", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 4, arrival_date: "2015-08-10", first_name: "adf", email: "afaf", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-10", first_name: "adsfa", email: "afda@gmaco.com", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-03", first_name: "afdsdfadfsa", email: "af", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-11", first_name: "df", email: "afd", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 1, arrival_date: "2015-08-04", first_name: "afda", email: "afd", date_range: nil, status: "pending"},
  {user_id: nil, spa_id: 9, arrival_date: "2015-08-04", first_name: "", email: "", date_range: nil, status: "pending"}
])
ReservationGuestNight.create!([
  {reservation_id: 1, nights: 14, guests: 10}
])
Retreat.create!([
  {arrival_date: nil, spa_id: 1, group_leader_id: nil, name: nil, registered: nil, confirmed: nil, group_rates_at: 8, comp_stay_at: 12, facebook_url: nil, image: nil, facebook_image: nil, description: nil, paypal: nil},
  {arrival_date: nil, spa_id: 2, group_leader_id: nil, name: "Old ladies YO!", registered: nil, confirmed: nil, group_rates_at: 8, comp_stay_at: 12, facebook_url: nil, image: nil, facebook_image: nil, description: nil, paypal: nil},
  {arrival_date: nil, spa_id: 1, group_leader_id: nil, name: nil, registered: nil, confirmed: nil, group_rates_at: 8, comp_stay_at: 12, facebook_url: nil, image: nil, facebook_image: nil, description: nil, paypal: nil},
  {arrival_date: nil, spa_id: 3, group_leader_id: nil, name: nil, registered: nil, confirmed: nil, group_rates_at: 8, comp_stay_at: 12, facebook_url: nil, image: nil, facebook_image: nil, description: nil, paypal: nil},
  {arrival_date: nil, spa_id: 6, group_leader_id: nil, name: "Happy Retreat", registered: nil, confirmed: nil, group_rates_at: 8, comp_stay_at: 12, facebook_url: nil, image: nil, facebook_image: nil, description: nil, paypal: nil}
])
Spa.create!([
  {name: "Crayon Ranch", city: "Tucson", state: "AZ"},
  {name: "Crayon Ranch", city: "Lenox", state: "MA"},
  {name: "Ranch of the Door", city: "Tecate", state: "MX"},
  {name: "Orange Mountain", city: "St. George", state: "UT"},
  {name: "Mirabel Resort and Spa", city: "Tucson", state: "AZ"},
  {name: "The Redwoods at Ojai", city: "Ojai", state: "CA"},
  {name: "Lake Awesome Resort & Spa", city: "Lake Awesome", state: "TX"},
  {name: "Trypalu Yoga", city: "Lenox", state: "MA"}
])
